url=ENV_ACCOUNTIA_URL
email=ntnhan025@gmail.com
password=Password1234
invalid_email=testdeferp71@mailinator.com
invalid_password=Pass123456
maximum_company_email=testdeferp@mailinator.com
headless=false
report=path
screenshot_fail=true
screenshot_pass=true
screenshot_all=true
author=Nhan Nguyen
authentication=url_proxy
username_authen=username
password_authen=password
SCREENSHOT_PATH=reports/screenshots
RECORDVIDEO_PATH=reports/records
LOGGER=all
implicit_wait=30
page_load_timeout=30

GEMINI_API_KEY=ENV_GEMINI_API_KEY
